return {
  "stevearc/aerial.nvim",
  event = "BufReadPost",
  cmd = { "AerialToggle", "AerialOpen", "AerialNavToggle" },
  keys = {
    { "<leader>a", "", desc = "󱣱 Navigation" },
    { "<leader>at", "<cmd>AerialToggle!<CR>", desc = "Toggle Aerial (keep focus)" },
    { "<leader>al", "<cmd>AerialOpen! left<CR>", desc = "Open Aerial on Left" },
    { "<leader>ar", "<cmd>AerialOpen! right<CR>", desc = "Open Aerial on Right" },
    { "<leader>af", "<cmd>AerialOpen! float<CR>", desc = "Open Aerial as Float" },
    { "<leader>ac", "<cmd>AerialClose<CR>", desc = "Close Aerial" },
    { "<leader>aC", "<cmd>AerialCloseAll<CR>", desc = "Close All Aerial Windows" },
    { "<leader>ao", "<cmd>AerialOpenAll<CR>", desc = "Open Aerial for All Windows" },
    { "<leader>an", "<cmd>AerialNavToggle<CR>", desc = "Toggle Aerial Navigation Window" },
    { "<leader>aN", "<cmd>AerialNavOpen<CR>", desc = "Force Open Aerial Navigation" },
    { "<leader>aM", "<cmd>AerialNavClose<CR>", desc = "Force Close Aerial Navigation" },
    { "<leader>ai", "<cmd>AerialInfo<CR>", desc = "Print Aerial Debug Info" },
    { "<leader>a]", "<cmd>AerialNext<CR>", desc = "Jump to Next Symbol(Aerial)" },
    { "<leader>a[", "<cmd>AerialPrev<CR>", desc = "Jump to Previous Symbol(Aerial)" },
    { "<leader>ag", "<cmd>AerialGo!<CR>", desc = "Jump to Current Symbol (stay)" },
    { "<leader>fa", "<cmd>Telescope aerial<CR>", desc = "Telescope: Fuzzy Symbol Search" },
  },
  opts = {
    backends = { "lsp", "treesitter", "markdown", "man" },
    layout = {
      min_width = 28,
      max_width = { 40, 0.2 },
      default_direction = "prefer_right",
    },
    attach_mode = "global",
    show_guides = true,
    highlight_on_hover = true,
    autojump = true,
    open_automatic = false,
    nerd_font = "auto",
  },
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-telescope/telescope.nvim",
  },
}
